FROM maven:3-jdk-8

LABEL maintainer="opensource@opstree.com"

WORKDIR /usr/src/app

ADD . /usr/src/app
RUN mvn clean install -Dmaven.test.skip=true

ENTRYPOINT ["java","-jar","/usr/src/app/target/helloworld-0.0.1-SNAPSHOT.jar"]
